version: '3'
services:
  admin:
    # image: 187480788971.dkr.ecr.us-east-1.amazonaws.com/kappa-espresso-production:${IMAGE_TAG:-latest}
    container_name: admin
    platform: linux/amd64
    build:
      context: .
      dockerfile: dev.Dockerfile
    env_file:
      - .env
    volumes:
      - /app
      # - /app/node_modules/
    # restart: always
    ports:
      - 3000:3000
    command:
      - /bin/sh
      - -c
      - |
        # Sync shared public files
        # rm -rf /app/shared/public/*
        # cp -r /app/public/* /app/public
        #
        # You can add more commands before startup: compile assets, run migrations, ... if you have
        # ...
        #
        # Start node app
        pwd
        ls app
        node server.js
    networks:
      - app-network
  nginx:
    image: nginx:alpine
    platform: linux/amd64
    # restart: always
    ports:
      - 80:80
    depends_on:
      - admin
    volumes:
      - /app
      - ../nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network

networks:
  app-network:
    external: true
